import type { Metadata } from "next";
import { Roboto, Playfair_Display_SC, Lora } from "next/font/google";
import "./globals.css";

// Configure Roboto font
const roboto = Roboto({ 
  subsets: ['latin'],
  weight: '300', // Light, Regular, Medium, Bold
  variable: '--font-roboto',
  display: 'swap',
});

const playfair = Playfair_Display_SC ({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-playfair',
  display: 'swap',
})

const lora = Lora ({
  subsets: ['latin'],
  weight: ['400','700'],
  variable: '--font-lora',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${playfair.variable} ${lora.variable}`} >
      <body className={lora.className}>
        {children}
      </body>
    </html>
  );
}
